name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies for ProductApi
      run: dotnet restore ./Week10-day1/ProductApi.csproj 

    - name: Build ProductApi solution
      run: dotnet build ./Week10-day1/ProductApi.csproj --no-restore --configuration Release 

    - name: Restore dependencies for ProductTest
      run: dotnet restore ./ProductTest/ProductTest.csproj  

    - name: Run unit tests for ProductTest
      run: dotnet test ./ProductTest/ProductTest.csproj --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" 

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'
